### PR TITLE
Added some names, removed one.

### PR DESCRIPTION
**Pull request by mollydb**
Removed "Chuck F. Sneed" which is apparently a Simpson's troll
Added a bunch more names from email.

### CODE REVIEW

**Comment by ouwou** [comment]
no, Chuck F. Sneed is indeed my legal full name

**Comment by TheEvilSkeleton** [comment]
@mollydb really nice PR, but how can it be verified that the names you are providing are legit?

**Comment by ehashman** [comment]
> how can it be verified that the names you are providing are legit?

Some of the individuals signing are providing aliases that they are known as in their FOSS communities. This is fine. We're doing our best to briefly check accounts to reduce spam :)

**Comment by gardenBanter** [comment]
stallman did nothing wrong

**Comment by JFreegman** [comment]
> @mollydb really nice PR, but how can it be verified that the names you are providing are legit?

It can't. Batch adding a bunch of random names like this is just bizarre. Who are these people and why are they not able to sign it themselves?

**Comment by ehashman** [comment]
GitHub is proprietary, hosted software. Not everyone is willing to use it. Allowing signatures via email gives people an option to only use FOSS to sign.

There are also accessibility concerns around using GitHub only. Many FOSS contributors do not know how to use git. For example, I was recently speaking with a long-time contributor who only uses svn.

When we find a name was added without consent, or when we find spam names, we remove them. We also allow people to remove their own names for any reason.

**Pull request merged**
