### PR TITLE
Add FSF response

### PR DESCRIPTION
**Pull request by ehashman**

### CODE REVIEW

**Comment by amiryal** [comment]
You added the statement:
> We stand by our call to action in the letter below.

I do not mind leaving my signature on the original letter with its original context for archival purposes, but in light of recent developments I no longer stand by the call to action. They have made their final decision against our appeal, but I respect that.

Please remove either this statement or my signature from the website. Thanks!

**Comment by ehashman** [comment]
@amiryal removed in #2561, let me know if you need anything else.

**Comment by xsrp** [comment]
I would also like to remove my signature for such reason. I no longer find it applicable.

**Comment by ehashman** [comment]
Done in #2563.

**Comment by AKurushimi** [comment]
I would also like for my signature to be removed for the same reason.

**Comment by ehashman** [comment]
@AKurushimi if you are able to comment here you are also able to submit a PR to do it yourself.

**Pull request merged**
