### PR TITLE
Complete Persian Translation and Signed by Me and Mohammad Bagher Abiat

### PR DESCRIPTION
**Pull request by System0x20**

### CODE REVIEW

**Comment by neilmcgovern** [comment]
There's a fair few conflicts here. Could this be:
1. rebased to the latest commit
2. split between signing and the translation?

**Comment by System0x20** [comment]
Ofcourse

**Comment by neilmcgovern** [comment]
Also, does this incorporate #2226 ?

**Comment by System0x20** [comment]
No this is entire rewritten. 2226 and the previous one by peylight (current translation) has too many errors for example "free" is translated as "رایگان" which means free as in free beer the correct word to use is "آزاد" which means free as in freedom. So I totally rewrote the thing and added a persian translation for appendix

**Comment by neilmcgovern** [comment]
> No this is entirely rewritten. 2226 and the previous one by peylight (current translation) has too many errors for example "free" is translated as "رایگان" which means free as in free beer the correct word to use is "آزاد" which means free as in freedom. So I totally rewrote the thing and added a persian translation for appendix
> 

Ok, thanks! I'll close that other one then

> P.S: I'm not good with git so I asked someone else to rebase the thing this may take a while to fix

No problems :)

**Comment by System0x20** [comment]
Rebasing somehow managed to get my friend's name right into index.md but not mine but I had enough of these git nonsense. this is it the translation is done, MB Abiat is there github says it doesnt conflict with anything

**Comment by neilmcgovern** [comment]
Thank you!

**Pull request merged**
