### PR TITLE
adding myself

### PR DESCRIPTION
**Pull request by domagalski**

### CODE REVIEW

**Comment by domagalski** [comment]
according to [this commit](https://github.com/rms-open-letter/rms-open-letter.github.io/commit/5f6ad451303f01a2db62a8d9f283a0bbfd93829e), my name should have been added, as it was less than number 466, but it appears that it didn't, despite some people signing after me getting added. Assuming that's an error. @shaunagm, mind merging this in during the next batch?

**Comment by shaunagm** [comment]
@domagalski yeah, that was a typo on my part - should have said up to 464. I'll get you in the next batch.

**Comment by shaunagm** [comment]
Thanks for flagging this, @domagalski! Not sure what happened.

**Comment by domagalski** [comment]
Thanks

**Pull request merged**
