### PR TITLE
Sign

### PR DESCRIPTION
**Pull request by sztomi**
*sigh*

### CODE REVIEW

**Comment by sztomi** [comment]
@ehashman can you explain why my signature wasn't merged?

**Comment by ehashman** [comment]
An oopsie ala https://github.com/rms-open-letter/rms-open-letter.github.io/issues/47#issue-839034136 I'll add you manually right now.

**Comment by ehashman** [comment]
Edit: you are on there. https://github.com/rms-open-letter/rms-open-letter.github.io/blame/main/index.md#L1233

**Comment by sztomi** [comment]
Thanks! (although that's not my name, I do see myself on the list now <3)

**Comment by ehashman** [comment]
I forgot to embed commit ID so I'm sure it's changed :sweat_smile: cheers

**Pull request closed without merging**
