### PR TITLE
Add personal signature

### PR DESCRIPTION
**Pull request by khionu**

### CODE REVIEW

**Comment by khionu** [comment]
Hi, why wasn't my name added to the signature list?

**Comment by ehashman** [comment]
I'll get you in the next batch, apologies. See https://github.com/rms-open-letter/rms-open-letter.github.io/issues/47#issue-839034136

**Comment by khionu** [comment]
I just had that brought to my attention. Thank you very much!

**Comment by ehashman** [comment]
Fixed: https://github.com/rms-open-letter/rms-open-letter.github.io/blame/60d422b3186a8e7811d2c809a224cbe67775b890/index.md#L190

**Pull request closed without merging**
