### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by Chaspen**

### CODE REVIEW

**Review by LaPingvino — CHANGES_REQUESTED** [review]
Too big change, accidentally removes contents

**Comment by neilmcgovern** [comment]
Something messed up with this PR, I've manually added your name in eb35444 instead.

**Comment by LaPingvino** [comment]
@neilmcgovern the github editor automatically renumbers. maybe add a note about not using the web editor? or somehow turn the markdown support for that file off?

**Comment by neilmcgovern** [comment]
There's already a note on how to do that in README.md. I don't think there's some magic runes to stop it happening in the editor though. It's not too bad to just manually add people.

**Pull request closed without merging**
