### PR TITLE
Add note about Stallman's opinion about "sex with child does harm one"

### PR DESCRIPTION
**Pull request by em92**
I don't agree with the letter, neither Stallman's behaviour, but want to add note to be more objective.

### CODE REVIEW

**Comment by em92** [comment]
I am not native English speaker, so suggestions welcome.

**Comment by neilmcgovern** [comment]
Moving this to a draft, as it's not just adding a name. This will need some more work and I don't want to accidentally merge it

**Comment by em92** [comment]
> This will need some more work

Just a note, @neilmcgovern. Doing no work with this PR for a long time means that organizers of this open letter or its sponsors, if any, deliberately do not want to be objective (for example, accepting this PR after Stallman's repeated resign from FSF). So you should put HIGHEST priority for reviewing this PR or make similar PR.

Why? This letter with reference is translated all over the world and this is like saying from UN Security Council "Some country has chemical weapon, so we must invade it", meanwhile there is no chemical weapon in this country.

**Comment by trinity-1686a** [comment]
On the other hand, modifying a document after it has been signed, by close to a thousand people now, is not an easy task, and should in my opinion not even be done, whatever the problem with it may be

**Comment by stackola** [comment]
> On the other hand, modifying a document after it has been signed, by close to a thousand people now, is not an easy task, and should in my opinion not even be done, whatever the problem with it may be

Wouldn't want to be too objective, I'm sure most people who signed this letter would agree.

**Comment by neilmcgovern** [comment]
Folks, unfortunately the phrasing of the letter is now frozen as it's been signed by a number of people. I don't think there's any more fruitful discussion to be had in this issue as we won't be changing it at this stage, sorry.

Also, a huge thank you to those in here who have kept discussion civil, unlike in other ones.

**Comment by em92** [comment]
> Folks, unfortunately the phrasing of the letter is now frozen as it's been signed by a number of people.

How about stop accepting new PRs, write a new letter with improvements (Stallman supporters found at least 3. See https://github.com/rms-support-letter/rms-support-letter.github.io/issues/175#issue-839598103), cleanup signatures and start accepting PRs for new letter?

**Comment by em92** [comment]
Bump @neilmcgovern just in case you unsubscribed from this thread.

**Comment by evrial** [comment]
hi @neilmcgovern how is your day going, i see open source community doing fantastic job, i wish you a wonderful day, god bless you and your family

**Comment by mollydb** [comment]
We made a note on the appendix, complete with timestamp: https://rms-open-letter.github.io/appendix

**Pull request closed without merging**
