### PR TITLE
Add myself (nicoo)

### PR DESCRIPTION
**Pull request by nbraud**

### CODE REVIEW

**Comment by nbraud** [comment]
... Github, why did you remove 4 lines at random?

**Comment by MrPetovan** [comment]
Maybe you didn't branch from the latest?

**Comment by nbraud** [comment]
Fixed

**Comment by nbraud** [comment]
> Maybe you didn't branch from the latest?

That wouldn't/shouldn't cause the commit to contain line deletions, though; I suspect that their web-based editor did something silly (presumably nobody tested it with multi-thousand lines files?) but I guess it doesn't matter much

**Pull request merged**
