### PR TITLE
add p tags for persian index

### LINKED ISSUE #2183: Fix text direction rendering on Persian translation
It is defaulting to LTR, should be RTL.

### PR DESCRIPTION
**Pull request by peylight**
to fix #2183 issue

### CODE REVIEW

**Comment by ehashman** [comment]
:ship:

**Comment by ehashman** [comment]
One final issue: looks like the links are now broken. Can you convert to `<a href=...>` format from markdown? :sweat:  sorry! I can do it if you don't have time.

**Comment by peylight** [comment]
@ehashman 
No problem, I will

**Comment by peylight** [comment]
@ehashman 
please check #2209

**Pull request merged**
